name: Update Index
on:
  workflow_dispatch:
  push:

concurrency: ci-index-${{ github.ref }}

permissions:
  contents: write


jobs:
  update-index:
    name: Update Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/script.js')
            console.log(await script({github, fetch}))
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'partitions/'
          # From https://github.community/t/github-actions-bot-email-address/17204/5
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          author_name: "commit-bot"
          message: "Scheduled data update from Github Actions"
          push: true
          fetch: false
